## Multi Classification

## Importing Libraries

In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import joblib

## Using Scaled Data

In [2]:
df = pd.read_csv('TrainModelDataFinalScl.csv')

In [3]:
df['departure_delay'].quantile([0.5,0.80,0.90])

0.5    0.000000
0.8    0.286421
0.9    1.196689
Name: departure_delay, dtype: float64

In [4]:
def categorize_delay(delay):
    if delay == 0:
        return 'No Delay'
    elif delay < 0.3:
        return 'Short Delay'
    elif 0.3 <= delay <= 0.90:
        return 'Moderate Delay'
    else:
        return 'Long Delay'

In [6]:
y = df['departure_delay'].apply(categorize_delay)
X = df.drop(columns=['departure_delay'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
print(X_train.shape)
print(X_test.shape)

(41257, 84)
(10315, 84)


## Logistic Regression

In [9]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [10]:
joblib.dump(model, 'Logistic_regressor_multi.pkl')

['Logistic_regressor_multi.pkl']

In [11]:
accuracy = accuracy_score(y_test, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average=None)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nPrecision, Recall, F1-Score for each class:")
for idx, category in enumerate(model.classes_):
    print(f"{category} - Precision: {precision[idx]:.4f}, Recall: {recall[idx]:.4f}, F1-Score: {f1[idx]:.4f}")

print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.7524

Precision, Recall, F1-Score for each class:
Long Delay - Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000
Moderate Delay - Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000
No Delay - Precision: 0.7524, Recall: 1.0000, F1-Score: 0.8587
Short Delay - Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000

Confusion Matrix:
[[   0    0 1310    0]
 [   0    0  670    0]
 [   0    0 7761    0]
 [   0    0  574    0]]


D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Using Unscaled Data

In [12]:
df = pd.read_csv('TrainModelDataFinalNotScl.csv')

In [13]:
def categorize_delay(delay):
    if delay == 0:
        return 'No Delay'
    elif delay < 45:
        return 'Short Delay'
    elif 45 <= delay <= 175:
        return 'Moderate Delay'
    else:
        return 'Long Delay'

In [14]:
y = df['departure_delay'].apply(categorize_delay)
X = df.drop(columns=['departure_delay'])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
print(X_train.shape)
print(X_test.shape)

(41257, 84)
(10315, 84)


## Logistic Regression

In [17]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [18]:
joblib.dump(model, 'Logistic_regressor_multiNotScl.pkl')

['Logistic_regressor_multiNotScl.pkl']

In [19]:
accuracy = accuracy_score(y_test, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average=None)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nPrecision, Recall, F1-Score for each class:")
for idx, category in enumerate(model.classes_):
    print(f"{category} - Precision: {precision[idx]:.4f}, Recall: {recall[idx]:.4f}, F1-Score: {f1[idx]:.4f}")

print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.9010

Precision, Recall, F1-Score for each class:
Moderate Delay - Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000
No Delay - Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000
Short Delay - Precision: 0.9011, Recall: 0.9999, F1-Score: 0.9479

Confusion Matrix:
[[   0    0   92]
 [   0    0  928]
 [   0    1 9294]]


D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
