# Binary Classification

## Using Scaled Data

In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import joblib

In [2]:
df = pd.read_csv('TrainModelDataFinalScl.csv')

In [3]:
y = df['departure_delay'].apply(lambda x: 'on-time' if x == 0 else 'delayed')
X = df.drop(columns=['departure_delay'])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
print(X_train.shape)
print(X_test.shape)

(41257, 84)
(10315, 84)


## Random Forest Classifier

In [6]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [7]:
joblib.dump(model, 'random_forest_classifier_binary.pkl')

['random_forest_classifier_binary.pkl']

In [8]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label="delayed")
recall = recall_score(y_test, y_pred, pos_label="delayed")
f1 = f1_score(y_test, y_pred, pos_label="delayed")
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.77
Precision: 0.55
Recall: 0.44
F1-Score: 0.49
Confusion Matrix:
[[1125 1429]
 [ 936 6825]]


## Logistic Regression

In [9]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [10]:
joblib.dump(model, 'Logistic_regressor_binary.pkl')

['Logistic_regressor_binary.pkl']

In [11]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label="delayed")
recall = recall_score(y_test, y_pred, pos_label="delayed")
f1 = f1_score(y_test, y_pred, pos_label="delayed")
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.75
Precision: 0.58
Recall: 0.04
F1-Score: 0.07
Confusion Matrix:
[[  96 2458]
 [  70 7691]]


## Using Not Scaled Data

In [12]:
df = pd.read_csv('TrainModelDataFinalNotScl.csv')

In [13]:
df.head()

,Temperature (°F)avg,Temperature (°F)Max,Temperature (°F)Min,Humidity (%)avg,Humidity (%)Max,Humidity (%)Min,Wind Speed (mph)avg,Wind Speed (mph)Max,Wind Speed (mph)Min,Pressure (in)avg,...,Hour_15,Hour_16,Hour_17,Hour_18,Hour_19,Hour_20,Hour_21,Hour_22,Hour_23,departure_delay
0,0.819952,0.605995,0.965468,0.827797,0.531856,1.089088,-0.095441,-0.329007,-0.345092,-0.454550,...,False,False,False,False,False,True,False,False,False,0.00
1,0.900366,0.605995,1.079867,0.691515,0.180001,1.089088,1.164024,0.068143,-0.345092,-0.454550,...,True,False,False,False,False,False,False,False,False,13.48
2,0.712734,0.605995,0.793870,0.530455,0.109630,0.709605,0.624254,-0.170147,-0.345092,-0.180812,...,False,False,False,False,False,False,False,False,False,13.48
3,0.732838,0.476480,0.908269,0.914521,1.305935,0.872240,0.624254,0.068143,-0.345092,-0.180812,...,False,False,False,False,False,False,False,False,True,21.00
4,0.819952,0.605995,0.965468,0.827797,0.531856,1.089088,-0.095441,-0.329007,-0.345092,-0.454550,...,False,False,False,False,False,False,False,False,False,13.48


In [14]:
y = df['departure_delay'].apply(lambda x: 'on-time' if x == 0 else 'delayed')
X = df.drop(columns=['departure_delay'])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
print(X_train.shape)
print(X_test.shape)

(41257, 84)
(10315, 84)


## Random Forest Classifier

In [17]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [18]:
joblib.dump(model, 'random_forest_classifier_binaryNotScl.pkl')

['random_forest_classifier_binaryNotScl.pkl']

In [19]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label="delayed")
recall = recall_score(y_test, y_pred, pos_label="delayed")
f1 = f1_score(y_test, y_pred, pos_label="delayed")
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.91
Precision: 0.94
Recall: 0.96
F1-Score: 0.95
Confusion Matrix:
[[9039  348]
 [ 581  347]]


## Logistic Regression

In [20]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [21]:
joblib.dump(model, 'Logistic_regressor_binaryNotScl.pkl')

['Logistic_regressor_binaryNotScl.pkl']

In [22]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label="delayed")
recall = recall_score(y_test, y_pred, pos_label="delayed")
f1 = f1_score(y_test, y_pred, pos_label="delayed")
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.91
Precision: 0.91
Recall: 1.00
F1-Score: 0.95
Confusion Matrix:
[[9386    1]
 [ 928    0]]
